PortfolioApp/urls.py
from django.urls import path, include
from .views import UserPortfolioUpdateView, UserListView, UserDetailView

app_name='PortfolioApp'

urlpatterns = [
    path('update/', UserPortfolioUpdateView.as_view(), name='update'),
    path('list/', UserListView.as_view(), name='list'),
    path('<slug:slug>/', UserDetailView.as_view(), name='detail'), 
]

Portfolio_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from PortfolioApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('app/', include('PortfolioApp.urls')),
    path('', views.index.as_view(), name='index'),    
]

PortfolioApp/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class UserPortfolio(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE, related_name='userportfolio')
    bio= models.CharField(max_length=50, blank=True,null=True)
    phone_number = PhoneNumberField(unique=True, blank=True, null=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank= True, null=True)
    twitter_username= models.CharField(max_length=50, blank=True,null=True)
    facebook_username= models.CharField(max_length=50, blank=True,null=True)
    linkedin_username= models.CharField(max_length=50, blank=True,null=True)
    github_username= models.CharField(max_length=50, blank=True,null=True)

    
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('PortfolioApp:list')

    def __str__(self):
        return self.user.username


class UserProject(models.Model):
    user=models.OneToOneField(UserPortfolio, on_delete=models.CASCADE)
    project_name= models.CharField(max_length= 150)
    project_description=models.TextField()
    link=models.URLField(blank=True,help_text="Please enter the URL of your project page.")

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('PortfolioApp:userprofile.html')

    def __str__(self):
        return self.project_name

@receiver (post_save, sender=User)
def create_userprofile(sender, instance, created ,**kwargs):
    if created:
        UserPortfolio.objects.create(user=instance)

@receiver (post_save, sender=User)
def save_userprofile(sender, instance, created, **kwargs):
    instance.userportfolio.save()

@receiver (post_save, sender=UserPortfolio)
def create_userproject(sender, instance, **kwargs):
    if True:
        UserProject.objects.create(user=instance)

@receiver (post_save, sender=UserPortfolio)
def save_userproject(sender, instance, created, **kwargs):
    instance.userproject.save()
    

PortfolioApp/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import UserPortfolio, UserProject
from django.views.generic import CreateView, TemplateView, UpdateView, ListView, DetailView
from django.contrib.auth.models import User
from django.db import models
# Create your views here.

app_name='PortfolioApp'


class index(TemplateView):
    template_name = "PortfolioApp/index.html"


class UserPortfolioUpdateView(LoginRequiredMixin, UpdateView):
    #permission needed here
    model = UserPortfolio
    fields= ['linkedin_username','phone_number', 'github_username','twitter_username','facebook_username','profile_pic']
    template_name = "PortfolioApp/userportfolio.html"

    def get_object(self):
        try:
            userportfolio = UserPortfolio.objects.get(pk=self.request.GET.get('pk'))
        except UserPortfolio.DoesNotExist:
            user = None
        


class UserListView(LoginRequiredMixin, ListView):
    model= UserPortfolio
    template_name= 'PortfolioApp/userlist.html'
    context_object_name='user_list'


class UserDetailView(LoginRequiredMixin, DetailView): 
    # specify the model to use 
    model = UserPortfolio
    context_object_name='user_detail'
    slug_field = 'id'
    template_name='PortfolioApp/userdetail.html'

PortfolioApp/templates/PortfolioApp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PortfolioApp</title>
</head>
<body>
    
    <h2>This is the index page</h2>
</body>
</html>

PortfolioApp/templates/PortfolioApp/userdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Detail of {{user_detail.user.username}}</h2>
    <h1>{{ user_detail.bio }}</h1> 
<p>{{ object. }}</p>
</body>
</html>

PortfolioApp/templates/PortfolioApp/userlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul> 
        <h2>This is a list of user:</h2>
        <!-- Iterate over object_list -->
        {% for object in user_list %} 
        <!-- Display Objects -->
        <li><a href="{% url 'PortfolioApp:detail' user_detail.slug %}">{{ object.user.username }}</a></li> 
        <li>{{ object.phone_number }}</li> 
      
        <hr/> 
        <!-- If object_list is empty  -->
        {% empty %} 
        <li>No objects yet.</li> 
        {% endfor %} 
    </ul> 
</body>
</html>

PortfolioApp/templates/PortfolioApp/userportfolio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

<form method="POST" enctype="multipart/form-data">

    {%csrf_token%}
    {{form.as_p}}

    <input type="submit" value="Save">

</form>

</body>
</html>